python3 CSPBusSeats.py CSP-tests/students_7disabled.txt
python3 CSPBusSeats.py CSP-tests/students_tests.txt
python3 CSPBusSeats.py CSP-tests/students2.txt
python3 CSPBusSeats.py CSP-tests/students3.txt
python3 CSPBusSeats.py CSP-tests/students_9troubled.txt
python3 CSPBusSeats.py CSP-tests/students33people.txt
python3 CSPBusSeats.py CSP-tests/students_CXandXRsiblings.txt
python3 CSPBusSeats.py CSP-tests/students_5TroubledSameYear.txt
python3 CSPBusSeats.py CSP-tests/students_4troubledSameYear.txt
python3 CSPBusSeats.py CSP-tests/studentsHighId.txt
python3 CSPBusSeats.py CSP-tests/elo.txt